; ----------------------------------------------------------------------------------------
; FILE: isr.asm
; PURPOSE: Autogenerated Interrupt Service Routines, called whenever an interrupt/exception fires.
; PROJECT: DragonWare Kernel
; DATE: 08-2025
; AUTHOR: Aggelos Tselios <aggelostselios777@gmail.com>
; LICENSE: GPL-v3.0-or-later, see COPYING in the toplevel directory
; ----------------------------------------------------------------------------------------

; Note (In case you're confused about what goes on here and what all these pushes and pops are):
; Every ISR creates a stack frame that looks like this (See interrupts.h for more details):
; typedef struct _InterruptStackFrame {
;        u32 gs, fs, es, ds;
;        u32 edi, esi, ebp, esp, ebx, edx, ecx, eax;
;        u32 int_no;
;        u32 err_code;
;        u32 eip, cs, eflags;
;        u32 useresp, ss;
; } InterruptStackFrame;
;
; The struct can be found under ddk/ia32/interrupts.h (or just interrupts.h, this is in the same directory as this file)
; It is used to save the entire state of the thread, handle the interrupt and then restore the state as if nothing happened.
; Note that it is not required that InterruptServiceHandler will return IMMEDIATELY. The scheduler may choose to swap to another thread,
; in which case this interrupt will be returned from when the thread receives CPU time again.
; I saw this being done in ReactOS (Albeit in a much more advanced, neat technique) and I refactored the whole thing to work like this.
; It was much harder to get right, but also cleaner to look at.

; This routine is shared among most ISRs, so easier to have it as a separate routine
; and jump into it after handling the few details of every different ISR
section .text
extern  InterruptServiceHandler
extern  NeedsResched
extern  ScheduleNext

PrepareInterruptFrame:
        pushad                          ; Save the GPRs
        push	ds                      ; Also save the segment registers
	push	es
	push	fs
	push	gs

        mov     ax,     0x10            ; Set up kernel data selectors
        mov     ds,     ax
        mov     es,     ax
        mov     fs,     ax
        mov     gs,     ax

        mov     eax,    esp             ; Now the stack frame is ready...
        push    eax                     ; so time to pass it to InterruptServiceHandler
        call    InterruptServiceHandler ; The function responsible for handling the interrupt (Rather, selecting a registered interrupt handler)
        add     esp,    4               ; Discard the argument we pushed.

        mov     eax,    [NeedsResched]  ; Check if we can return safely or we need to reschedule
        test    eax,    eax             ; Is NeedResched 0 or not?
        jnz     .ScheduleNext           ; If we jump here, we will only return to this function once the current thread is scheduled again
.ReturnFromInterrupt:
        pop     gs                      ; Now "restore" the segment registers (Whatever the function actually gave us)
        pop     fs
        pop     es
        pop     ds
        popad                           ; "Restore" the GPRs of whatever we got from that stack too
        add     esp,    8               ; Discard the error code and interrupt number, we don't want them

        iret                            ; And jump back to the newly selected task! (Or the old one, if it still has processing time)
.ScheduleNext:
        call    ScheduleNext
        jmp     .ReturnFromInterrupt

; Interrupt that did not push an error code, so we
; have to fix up the stack by pushing a fake one.
%macro DECLARE_ISR_NOERR 1
global InterruptServiceRoutine%1
InterruptServiceRoutine%1:
        push dword 0        ; fake error code to match expect IDTRegister stack layout,
        push dword %1       ; the actual interrupt number
        jmp PrepareInterruptFrame
%endmacro

; Interrupt that also pushed an error code, so we only need to provide the
; interrupt number and jump into PrepareInterruptFrame
%macro DECLARE_ISR_WITHERR 1
global InterruptServiceRoutine%1
InterruptServiceRoutine%1:
        push dword %1
        jmp PrepareInterruptFrame
%endmacro

; Now time to generate the actual ISRs
; For which ISRs need an error code and which ones provide one on their own,
; the Intel Developer Manuals must be consulted.
DECLARE_ISR_NOERR       0
DECLARE_ISR_NOERR       1
DECLARE_ISR_NOERR       2
DECLARE_ISR_NOERR       3
DECLARE_ISR_NOERR       4
DECLARE_ISR_NOERR       5
DECLARE_ISR_NOERR       6
DECLARE_ISR_NOERR       7
DECLARE_ISR_WITHERR     8
DECLARE_ISR_NOERR       9
DECLARE_ISR_WITHERR     10
DECLARE_ISR_WITHERR     11
DECLARE_ISR_WITHERR     12
DECLARE_ISR_WITHERR     13
DECLARE_ISR_WITHERR     14
DECLARE_ISR_NOERR       15
DECLARE_ISR_NOERR       16
DECLARE_ISR_WITHERR     17
DECLARE_ISR_NOERR       18
DECLARE_ISR_WITHERR     19
DECLARE_ISR_NOERR       20
DECLARE_ISR_NOERR       21
DECLARE_ISR_NOERR       22
DECLARE_ISR_NOERR       23
DECLARE_ISR_NOERR       24
DECLARE_ISR_NOERR       25
DECLARE_ISR_NOERR       26
DECLARE_ISR_NOERR       27
DECLARE_ISR_NOERR       28
DECLARE_ISR_NOERR       29
DECLARE_ISR_WITHERR     30
DECLARE_ISR_NOERR       31

; IRQ code
DECLARE_ISR_NOERR       32
DECLARE_ISR_NOERR       33
DECLARE_ISR_NOERR       34
DECLARE_ISR_NOERR       35
DECLARE_ISR_NOERR       36
DECLARE_ISR_NOERR       37
DECLARE_ISR_NOERR       38
DECLARE_ISR_NOERR       39
DECLARE_ISR_NOERR       40
DECLARE_ISR_NOERR       41
DECLARE_ISR_NOERR       42
DECLARE_ISR_NOERR       43
DECLARE_ISR_NOERR       44
DECLARE_ISR_NOERR       45
DECLARE_ISR_NOERR       46
DECLARE_ISR_NOERR       47

; And the DragonWare syscalls, when done using software interrupts
; 0x60 is native syscalls - 0x80 will be reserved for some POSIX syscalls maybe
DECLARE_ISR_NOERR       0x60
DECLARE_ISR_NOERR       0x80
