set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ARCH)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(CMAKE_C_COMPILER clang CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_NASM_COMPILER nasm CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER ld.lld CACHE FILEPATH "" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(ARCH "IA32")

set(CMAKE_USER_MAKE_RULES_OVERRIDE "${CMAKE_CURRENT_LIST_DIR}/CompilerOverrides.cmake")
