set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ARCH)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_C_COMPILER i686-elf-gcc CACHE FILEPATH "")
set(CMAKE_ASM_NASM_COMPILER nasm CACHE FILEPATH "")
set(CMAKE_LINKER i686-elf-ld CACHE FILEPATH "")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(ARCH "IA32")

set(CMAKE_USER_MAKE_RULES_OVERRIDE "${CMAKE_CURRENT_LIST_DIR}/CompilerOverrides.cmake")
execute_process(COMMAND ${CMAKE_C_COMPILER} -dumpversion OUTPUT_VARIABLE GCC_VERSION)
