set(GRUB_ISO_DIR ${CMAKE_CURRENT_BINARY_DIR}/GRUB)
set(RUN_DIR ${GRUB_ISO_DIR}/RUN)
set(SYSTEM_DIR ${GRUB_ISO_DIR}/SYSTEM)
set(GRUB_CFG_DIR ${GRUB_ISO_DIR}/boot/grub/)

file(MAKE_DIRECTORY ${GRUB_ISO_DIR})
file(MAKE_DIRECTORY ${RUN_DIR})
file(MAKE_DIRECTORY ${SYSTEM_DIR})
file(MAKE_DIRECTORY ${GRUB_CFG_DIR})

file(COPY_FILE ${CMAKE_SOURCE_DIR}/bootmanager/grub.cfg ${GRUB_CFG_DIR}/grub.cfg)

get_property(USER_BINARIES_LIST GLOBAL PROPERTY DRAGONWARE_USER_BINARIES)
get_property(USER_TARGET_LIST GLOBAL PROPERTY DRAGONWARE_USER_TARGETS)

add_custom_command(
    OUTPUT ${BOOTCD}
    COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:kernel.sys> ${SYSTEM_DIR}/KRNLIA32.SYS
    COMMAND ${CMAKE_COMMAND} -E copy ${USER_BINARIES_LIST} ${RUN_DIR}
    COMMAND grub-mkrescue -o ${BOOTCD} ${GRUB_ISO_DIR}
    DEPENDS kernel.sys ${USER_TARGET_LIST}
    COMMENT "Generatint GRUB-based ISO..."
)

add_custom_target(bootcd ALL DEPENDS ${BOOTCD})
