name: Complete DragonWare Build (Kernel + Userland + Boot Manager)

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Set build date
        run: echo "BUILD_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Set build tag
        run: |
          echo "BUILD_TAG=$(date +%Y-%m-%d-%H%M%S)-nightly-${GITHUB_RUN_ID}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache toolchain
        uses: actions/cache@v3
        with:
          path: /usr/local/i686-elf-tools
          key: i686-elf-toolchain-15.2.0

      - name: Install i686-elf toolchain
        run: |
          if [ ! -d /usr/local/i686-elf-tools ]; then
            wget -nv https://github.com/lordmilko/i686-elf-tools/releases/download/15.2.0/i686-elf-tools-linux.zip
            unzip -qq i686-elf-tools-linux.zip -d i686tools
            sudo mkdir -p /usr/local/i686-elf-tools
            sudo cp -r i686tools/* /usr/local/i686-elf-tools/
          fi

      - name: Add toolchain to PATH
        run: echo "/usr/local/i686-elf-tools/bin" >> $GITHUB_PATH


      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build nasm xorriso            

      - name: Build DragonWare Components
        run: |
          echo "1" > sys/BUILDID

          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -GNinja \
            -DUSE_CLANG_COMPILER=OFF \
            -DLEGACY_SUPPORT=OFF

          cmake --build build --target everything -j$(nproc)
